config/routes.rb
require 'api_constraints'

WashCostApp::Application.routes.draw do
  use_doorkeeper do
    #controllers :applications => 'applications'
  end
  

  match '/infographic' => 'infographic#index'
  match '/infographic/mobile' => 'mobile#infographic'

  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      #devise_for :users

      get '/me' => 'users#me'
      get '/reports' => 'users#reports'
      get '/report/:id' => 'users#reports'

      scope '/water' do
        post '/create' => 'water#create'
        post '/update/:id' => 'water#update'
      end

      scope '/sanitation' do
        post '/create' => 'sanitation#create'
        post '/update/:id' => 'sanitation#update'
      end

      match '*not_found', to: 'base#api_not_found'
    end
  end

  scope "(:locale)", :locale => /en|fr|bn/ do

    devise_scope :user do
      get 'users' => 'authentication/registrations#new'
    end

    devise_scope :user do
      get 'users/password' => 'authentication/passwords#new'
    end

    devise_for :users, :controllers => { :sessions => 'authentication/sessions', :registrations => 'authentication/registrations', :passwords => 'authentication/passwords' }

    resources :dashboard

    scope '/calculators' do

      namespace :basic do

        scope '/water' do
          get '/begin' => 'water#begin', :as => 'water_begin'
          get '/report' => 'water#report', :as => 'water_report'
          get '/report/save' => 'water#save_report', :as => 'water_save_report'
          post '/report/save' => 'water#store_report', :as => 'water_store_report'
          get '/report/share' => 'water#share_report', :as => 'water_share_report'
          get '/:section' => 'water#questionnaire', :as => 'water_action'
          post '/update/:section' => 'water#update', :as => 'water_update'
          post '/dynamic_update' => 'water#dynamic_update', :as => 'water_dynamic_update'
          root :to => redirect( '/%{locale}/calculators/basic/water/country' ), :as => 'water'
        end

        scope '/sanitation' do
          get '/begin' => 'sanitation#begin', :as => 'sanitation_begin'
          get '/report' => 'sanitation#report', :as => 'sanitation_report'
          get '/report/save' => 'sanitation#save_report', :as => 'sanitation_save_report'
          post '/report/save' => 'sanitation#store_report', :as => 'sanitation_store_report'
          get '/report/share' => 'sanitation#share_report', :as => 'sanitation_share_report'
          get '/:section' => 'sanitation#questionnaire', :as => 'sanitation_action'
          post '/update/:section' => 'sanitation#update', :as => 'sanitation_update'
          post '/dynamic_update' => 'sanitation#dynamic_update', :as => 'sanitation_dynamic_update'
          root :to => redirect( '/%{locale}/calculators/basic/sanitation/country' ), :as => 'sanitation'
        end

      end

      namespace :advanced do

        scope '/water' do
          get '/begin' => 'water#begin', :as => 'water_begin'
          get '/report' => 'water#report', :as => 'water_report'
          get '/report/save' => 'water#save_report', :as => 'water_save_report'
          post '/report/save' => 'water#store_report', :as => 'water_store_report'
          get '/report/share' => 'water#share_report', :as => 'water_share_report'
          get '/:section' => 'water#questionnaire', :as => 'water_action'
          post '/update/:section' => 'water#update', :as => 'water_update'
          post '/dynamic_update' => 'water#dynamic_update', :as => 'water_dynamic_update'
          root :to => redirect( '/%{locale}/calculators/advanced/water/service_area' ), :as => 'water'
        end

        scope '/sanitation' do
          get '/begin' => 'sanitation#begin', :as => 'sanitation_begin'
          get '/report' => 'sanitation#report', :as => 'sanitation_report'
          get '/report/save' => 'sanitation#save_report', :as => 'sanitation_save_report'
          post '/report/save' => 'sanitation#store_report', :as => 'sanitation_store_report'
          get '/report/share' => 'sanitation#share_report', :as => 'sanitation_share_report'
          get '/:section' => 'sanitation#questionnaire', :as => 'sanitation_action'
          post '/update/:section' => 'sanitation#update', :as => 'sanitation_update'
          post '/dynamic_update' => 'sanitation#dynamic_update', :as => 'sanitation_dynamic_update'
          root :to => redirect( '/%{locale}/calculators/advanced/sanitation/service_area' ), :as => 'sanitation'
        end

      end

      post '/selection' => 'calculators#selection'

      root :to => 'calculators#index', :as => 'calculators'

    end

    get '/dashboard' => 'dashboard#index', :as => 'dashboard'
    get '/report/destroy/:id' => 'reports#destroy', :as => 'reports_destroy'
    get '/report/:id' => 'reports#load', :as => 'reports_load'
    put '/report' => 'reports#update', :as => 'report'

    root :to => 'landing#index', :as => 'localised_root'

  end

  root :to => redirect( "/#{I18n.default_locale}/" )

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  include ApplicationHelper

  authorize_resource DashboardController

  layout "general"

  def index
    @reports = current_user.user_reports
  end

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
  end
end

app/views/dashboard/index.html.haml
.boxed_container
  .boxed_content.page_content

    .dashboard

      .dashboard--profile

        .dashboard--profile--details
          .dashboard--profile--details--title= current_user.name
          .dashboard--profile--details--field
            = "#{t( 'dashboard.company' )}:"
            = current_user.company.present? ? current_user.company : 'Not specified'
          .dashboard--profile--details--field
            = "#{t( 'dashboard.country' )}:"
            = (current_user.country != nil && !current_user.country.empty? && Country.new(current_user.country).data.present?) ? Country.new(current_user.country).translations[I18n.locale.to_s].titleize : 'Not specified'
          .dashboard--profile--details--field
            = "#{t( 'dashboard.preferred_language' )}:"
            = current_user.prefered_language != nil ? options_for_languages[ options_for_languages.index{ |l| l[1] == current_user.prefered_language } ][0]  : ''
          .dashboard--profile--details--field
            = "#{t( 'dashboard.current_mail' )}:"
            = current_user.email

          = link_to t( 'edit' ), edit_user_registration_path(I18n.locale), :class => 'button dashboard--profile--user--button'

      %table.dashboard--report_table
        %thead
          %tr
            %th.dashboard--report_table--heading= t( 'dashboard.name' )
            %td.dashboard--report_table--heading{ :width => 20 }
            %th.dashboard--report_table--heading{ :width => 100 }= t( 'dashboard.location' )
            %th.dashboard--report_table--heading{ :width => 80 }= t( 'dashboard.date' )
            %th.dashboard--report_table--heading{ :width => 180 }= t( 'dashboard.calculator_type' )
            %th.dashboard--report_table--heading{ :width => 100 }= t( 'dashboard.service' )
            %th.dashboard--report_table--heading{ :width => 0 }

        %tbody
          - @reports.each do |report|
            %tr.dashboard--report_table--row
              %td.dashboard--report_table--cell= report.title
              %td.dashboard--report_table--cell
                - if report.questionnaire[ 'country' ].present?
                  %div{ :class => "flag flag-#{report.questionnaire['country'].downcase}" }
              %td.dashboard--report_table--cell
                -if  report.questionnaire[ 'country' ].present?
                  = Country.new( report.questionnaire["country"] ).name.truncate(13)
                - else
                  &mdash;
              %td.dashboard--report_table--cell= report.created_at.strftime( '%d.%m.%Y' )
              %td.dashboard--report_table--cell= t('calculators.' + report.level).capitalize + ' ' +  t('calculators.' + report.type).capitalize
              %td.dashboard--report_table--cell
                = form_for report, :url => report_path( I18n.locale ), :html => { 'data-dynamic_form' => report_path( I18n.locale ) } do |f|
                  = f.hidden_field :id
                  = f.select :status, options_for_select( options_for_report_statuses, report.status )
              %td.dashboard--report_table--cell.buttons
                = link_to t( 'buttons.view_report' ), reports_load_path( I18n.locale, report.id ), :class => 'button button-small'
                = link_to t( 'buttons.delete_report' ), reports_destroy_path( I18n.locale, report.id ), :class => 'button button-small report-delete'
            %tr.dashboard--report_table--row
              %td.dashboard--report_table--cell.additional-comparison{:colspan => 7}
                - if report.level == "basic"
                  %div
                    %em
                      &mdash;
                -else
                  %div
                    %em= t('dashboard.compare.label1')
                    = report["capital_expenditure_per_person"] != nil ? report["capital_expenditure_per_person"] : "N/A"
                    /= final_usd_2011(report.questionnaire, capital_expenditure_per_person(report.questionnaire)).to_s
                  %div
                    %em= t('dashboard.compare.label2')
                    = report["recurrent_expenditure_per_person_per_year"] != nil ? report["recurrent_expenditure_per_person_per_year"] : "N/A"
                    /= final_usd_2011(report.questionnaire, recurrent_expenditure_per_person_per_year(report.questionnaire, 30)).to_s
                  %div
                    %em= t('dashboard.compare.label3')
                    = report["population_meeting_all_national_service_norms"] != nil ? report["population_meeting_all_national_service_norms"] .to_s + '%' : '0%'
                    /= percentage_of_population_that_meets_all_norms(report.questionnaire).to_s + '%'