config/routes.rb
require 'api_constraints'

WashCostApp::Application.routes.draw do
  use_doorkeeper do
    #controllers :applications => 'applications'
  end
  

  match '/infographic' => 'infographic#index'
  match '/infographic/mobile' => 'mobile#infographic'

  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      #devise_for :users

      get '/me' => 'users#me'
      get '/reports' => 'users#reports'
      get '/report/:id' => 'users#reports'

      scope '/water' do
        post '/create' => 'water#create'
        post '/update/:id' => 'water#update'
      end

      scope '/sanitation' do
        post '/create' => 'sanitation#create'
        post '/update/:id' => 'sanitation#update'
      end

      match '*not_found', to: 'base#api_not_found'
    end
  end

  scope "(:locale)", :locale => /en|fr|bn/ do

    devise_scope :user do
      get 'users' => 'authentication/registrations#new'
    end

    devise_scope :user do
      get 'users/password' => 'authentication/passwords#new'
    end

    devise_for :users, :controllers => { :sessions => 'authentication/sessions', :registrations => 'authentication/registrations', :passwords => 'authentication/passwords' }

    resources :dashboard

    scope '/calculators' do

      namespace :basic do

        scope '/water' do
          get '/begin' => 'water#begin', :as => 'water_begin'
          get '/report' => 'water#report', :as => 'water_report'
          get '/report/save' => 'water#save_report', :as => 'water_save_report'
          post '/report/save' => 'water#store_report', :as => 'water_store_report'
          get '/report/share' => 'water#share_report', :as => 'water_share_report'
          get '/:section' => 'water#questionnaire', :as => 'water_action'
          post '/update/:section' => 'water#update', :as => 'water_update'
          post '/dynamic_update' => 'water#dynamic_update', :as => 'water_dynamic_update'
          root :to => redirect( '/%{locale}/calculators/basic/water/country' ), :as => 'water'
        end

        scope '/sanitation' do
          get '/begin' => 'sanitation#begin', :as => 'sanitation_begin'
          get '/report' => 'sanitation#report', :as => 'sanitation_report'
          get '/report/save' => 'sanitation#save_report', :as => 'sanitation_save_report'
          post '/report/save' => 'sanitation#store_report', :as => 'sanitation_store_report'
          get '/report/share' => 'sanitation#share_report', :as => 'sanitation_share_report'
          get '/:section' => 'sanitation#questionnaire', :as => 'sanitation_action'
          post '/update/:section' => 'sanitation#update', :as => 'sanitation_update'
          post '/dynamic_update' => 'sanitation#dynamic_update', :as => 'sanitation_dynamic_update'
          root :to => redirect( '/%{locale}/calculators/basic/sanitation/country' ), :as => 'sanitation'
        end

      end

      namespace :advanced do

        scope '/water' do
          get '/begin' => 'water#begin', :as => 'water_begin'
          get '/report' => 'water#report', :as => 'water_report'
          get '/report/save' => 'water#save_report', :as => 'water_save_report'
          post '/report/save' => 'water#store_report', :as => 'water_store_report'
          get '/report/share' => 'water#share_report', :as => 'water_share_report'
          get '/:section' => 'water#questionnaire', :as => 'water_action'
          post '/update/:section' => 'water#update', :as => 'water_update'
          post '/dynamic_update' => 'water#dynamic_update', :as => 'water_dynamic_update'
          root :to => redirect( '/%{locale}/calculators/advanced/water/service_area' ), :as => 'water'
        end

        scope '/sanitation' do
          get '/begin' => 'sanitation#begin', :as => 'sanitation_begin'
          get '/report' => 'sanitation#report', :as => 'sanitation_report'
          get '/report/save' => 'sanitation#save_report', :as => 'sanitation_save_report'
          post '/report/save' => 'sanitation#store_report', :as => 'sanitation_store_report'
          get '/report/share' => 'sanitation#share_report', :as => 'sanitation_share_report'
          get '/:section' => 'sanitation#questionnaire', :as => 'sanitation_action'
          post '/update/:section' => 'sanitation#update', :as => 'sanitation_update'
          post '/dynamic_update' => 'sanitation#dynamic_update', :as => 'sanitation_dynamic_update'
          root :to => redirect( '/%{locale}/calculators/advanced/sanitation/service_area' ), :as => 'sanitation'
        end

      end

      post '/selection' => 'calculators#selection'

      root :to => 'calculators#index', :as => 'calculators'

    end

    get '/dashboard' => 'dashboard#index', :as => 'dashboard'
    get '/report/destroy/:id' => 'reports#destroy', :as => 'reports_destroy'
    get '/report/:id' => 'reports#load', :as => 'reports_load'
    put '/report' => 'reports#update', :as => 'report'

    root :to => 'landing#index', :as => 'localised_root'

  end

  root :to => redirect( "/#{I18n.default_locale}/" )

end

app/controllers/landing_controller.rb
class LandingController < ApplicationController

  layout 'layouts/pre_application'

  def index

  end

end

app/views/landing/_footer.html.haml
%footer.preapplication_footer
  .page_content

    .preapplication_footer--content
      .preapplication_footer--links
        %a.preapplication_footer--link{ :href => infographic_path } About the life-cycle costs approach
        %a.preapplication_footer--link{ :href => "http://blog.washcost.org/washcost-calculator/" } WASHCost Blog
        %a.preapplication_footer--link{ :href => "http://www.washcost.info/" } washcost.info

      .preapplication_footer--social
        %a.preapplication_footer--social--item.preapplication_footer--social--item-facebook{ :href => "https://www.facebook.com/ircwash" }
        %a.preapplication_footer--social--item.preapplication_footer--social--item-twitter{ :href => "http://www.twitter.com/washcostcal" }
        %a.preapplication_footer--social--item.preapplication_footer--social--item-google{ :href => "" }

      .preapplication_footer--important
        %img.preapplication_footer--logo{ :src => asset_path("static/irc.png"), :alt => 'IRC' }
        %a.preapplication_footer--important--link{ :href => "" } Privacy Statement
        .preapplication_footer--important--link © IRC. All Rights Reserved

app/views/landing/_masthead.html.haml
%header.header
  .page_content
    .header--content

      = link_to localised_root_path( I18n.locale ), class: 'header--logo' do
        = image_tag 'image-logo.png', class: 'header--logo--image', :alt => 'WASHCost powered by IRC', :width => 200, :height => 38

      = link_to 'Try the WASHCost Calculator Beta', calculators_path( I18n.locale ), :class => 'header--primary_button button'

app/views/landing/index.html.haml
= content_for :title do
  The WASHCost Calculator

.homepage

  %h1.homepage--title WASHCost Calculator
  %p.homepage--subtitle
    Try the WASHCost Calculator Beta to plan
    %br/
    sustainable, long-lasting WASH services.

  .homepage--video
    %iframe{ :src => "https://player.vimeo.com/video/73270180?autoplay=false", :width => "800", :height => "451", :frameborder => "0", :webkitallowfullscreen => true, :mozallowfullscreen => true, :allowfullscreen => true }

  .homepage--buttons
    .homepage--buttons--item
      = link_to 'Try the WASHCost Calculator Beta', calculators_path, :class => 'homepage--button button button-secondary'
    .homepage--buttons--item
      = link_to 'Learn more about the life-cycle costs approach', infographic_path, :class => 'homepage--button button button-secondary'