config/routes.rb
require 'api_constraints'

WashCostApp::Application.routes.draw do
  use_doorkeeper do
    #controllers :applications => 'applications'
  end
  

  match '/infographic' => 'infographic#index'
  match '/infographic/mobile' => 'mobile#infographic'

  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      #devise_for :users

      get '/me' => 'users#me'
      get '/reports' => 'users#reports'
      get '/report/:id' => 'users#reports'

      scope '/water' do
        post '/create' => 'water#create'
        post '/update/:id' => 'water#update'
      end

      scope '/sanitation' do
        post '/create' => 'sanitation#create'
        post '/update/:id' => 'sanitation#update'
      end

      match '*not_found', to: 'base#api_not_found'
    end
  end

  scope "(:locale)", :locale => /en|fr|bn/ do

    devise_scope :user do
      get 'users' => 'authentication/registrations#new'
    end

    devise_scope :user do
      get 'users/password' => 'authentication/passwords#new'
    end

    devise_for :users, :controllers => { :sessions => 'authentication/sessions', :registrations => 'authentication/registrations', :passwords => 'authentication/passwords' }

    resources :dashboard

    scope '/calculators' do

      namespace :basic do

        scope '/water' do
          get '/begin' => 'water#begin', :as => 'water_begin'
          get '/report' => 'water#report', :as => 'water_report'
          get '/report/save' => 'water#save_report', :as => 'water_save_report'
          post '/report/save' => 'water#store_report', :as => 'water_store_report'
          get '/report/share' => 'water#share_report', :as => 'water_share_report'
          get '/:section' => 'water#questionnaire', :as => 'water_action'
          post '/update/:section' => 'water#update', :as => 'water_update'
          post '/dynamic_update' => 'water#dynamic_update', :as => 'water_dynamic_update'
          root :to => redirect( '/%{locale}/calculators/basic/water/country' ), :as => 'water'
        end

        scope '/sanitation' do
          get '/begin' => 'sanitation#begin', :as => 'sanitation_begin'
          get '/report' => 'sanitation#report', :as => 'sanitation_report'
          get '/report/save' => 'sanitation#save_report', :as => 'sanitation_save_report'
          post '/report/save' => 'sanitation#store_report', :as => 'sanitation_store_report'
          get '/report/share' => 'sanitation#share_report', :as => 'sanitation_share_report'
          get '/:section' => 'sanitation#questionnaire', :as => 'sanitation_action'
          post '/update/:section' => 'sanitation#update', :as => 'sanitation_update'
          post '/dynamic_update' => 'sanitation#dynamic_update', :as => 'sanitation_dynamic_update'
          root :to => redirect( '/%{locale}/calculators/basic/sanitation/country' ), :as => 'sanitation'
        end

      end

      namespace :advanced do

        scope '/water' do
          get '/begin' => 'water#begin', :as => 'water_begin'
          get '/report' => 'water#report', :as => 'water_report'
          get '/report/save' => 'water#save_report', :as => 'water_save_report'
          post '/report/save' => 'water#store_report', :as => 'water_store_report'
          get '/report/share' => 'water#share_report', :as => 'water_share_report'
          get '/:section' => 'water#questionnaire', :as => 'water_action'
          post '/update/:section' => 'water#update', :as => 'water_update'
          post '/dynamic_update' => 'water#dynamic_update', :as => 'water_dynamic_update'
          root :to => redirect( '/%{locale}/calculators/advanced/water/service_area' ), :as => 'water'
        end

        scope '/sanitation' do
          get '/begin' => 'sanitation#begin', :as => 'sanitation_begin'
          get '/report' => 'sanitation#report', :as => 'sanitation_report'
          get '/report/save' => 'sanitation#save_report', :as => 'sanitation_save_report'
          post '/report/save' => 'sanitation#store_report', :as => 'sanitation_store_report'
          get '/report/share' => 'sanitation#share_report', :as => 'sanitation_share_report'
          get '/:section' => 'sanitation#questionnaire', :as => 'sanitation_action'
          post '/update/:section' => 'sanitation#update', :as => 'sanitation_update'
          post '/dynamic_update' => 'sanitation#dynamic_update', :as => 'sanitation_dynamic_update'
          root :to => redirect( '/%{locale}/calculators/advanced/sanitation/service_area' ), :as => 'sanitation'
        end

      end

      post '/selection' => 'calculators#selection'

      root :to => 'calculators#index', :as => 'calculators'

    end

    get '/dashboard' => 'dashboard#index', :as => 'dashboard'
    get '/report/destroy/:id' => 'reports#destroy', :as => 'reports_destroy'
    get '/report/:id' => 'reports#load', :as => 'reports_load'
    put '/report' => 'reports#update', :as => 'report'

    root :to => 'landing#index', :as => 'localised_root'

  end

  root :to => redirect( "/#{I18n.default_locale}/" )

end

app/views/shared/_masthead.html.haml
%header.header
  .page_content
    .header--content

      = link_to calculators_path( I18n.locale ), :class => 'header--logo' do
        = image_tag 'image-logo.png', :class => 'header--logo--image', :alt => 'WASHCost powered by IRC', :width => 200, :height => 40

      %span.header--mobile_navigation_button

      %ul.header--links

        -#
          %li.header--links--item
            %a{ :href => "#", :class => "header--links--link" }=t( 'navigation.utility.about' )

          %li.header--links--item
            %a{ :href => "#", :class => "header--links--link" }=t( 'navigation.utility.contact' )

        %li.header--links--item.header--links--item-dropdown
          %a{ :href => "#", :class => "header--links--link header--links--link-dropdown" }=t( 'navigation.utility.language' )
          %ul.header--links--item--dropdown
            - options_for_languages.each do |language|
              %li.header--links--item--dropdown--item
                = link_to language[0], ((request.path.count("/") == 1) ? "/#{language[1]}#{request.path}" : request.path.gsub( /^\/[^\/]+/, "/#{language[1]}" )), :class => "header--links--item--dropdown--link #{'header--links--item--dropdown--link-active' unless language[1] != I18n.locale.to_s}"

        - if user_signed_in? && current_user
          %li.header--links--item
            = link_to (current_user.first_name && !current_user.first_name.empty?) ? "#{current_user.first_name} #{current_user.last_name}".split.map(&:capitalize).join(' ') : current_user.email.split('@')[0], dashboard_path(I18n.locale), class: 'header--links--link header--links--link-special'
          %li.header--links--item
            = link_to t('navigation.utility.sign_out'), destroy_user_session_path( I18n.locale ), method: :delete, class: 'header--links--link header--links--link-special'
        - else
          %li.header--links--item
            = link_to t('navigation.utility.sign_in'), new_user_session_path( I18n.locale ), class: 'header--links--link header--links--link-special'

app/views/shared/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String) && name.to_s=='alert'
    .alert-box{"data-alert" => ""}
      #{msg}
      %a.close{:href => "#"} ×

app/views/shared/save_report.html.haml
.boxed_container.boxed_container-full_height
  .boxed_content
    .page_content

      = form_for @report, :url => footer_save_report_url, :html => { :class => 'standalone_form' } do |f|

        %h1.standalone_form--heading= t 'report.save_your_report'

        = render "devise/shared/messages"

        .standalone_form--field.standalone_form--field-text
          = f.text_field :title, { :class => 'standalone_form--field--input standalone_form--field--input-text', :placeholder => t( 'report.save_input' ) }

        .standalone_form--footer
          .standalone_form--buttons.standalone_form--buttons-centred
            = f.submit t( 'report.save_submit' ), :class => 'button'

app/views/shared/share_report.html.haml
.boxed_container
  .boxed_content.page_content

    %h1.standalone_form--heading= t 'report.share_your_report'

    .share_report
      %a.share_report--link{ :href => "http://www.ircwash.org/projects/life-cycle-costing-tools?id=" + reports_load_path( I18n.locale, @report.id ) }= "http://www.ircwash.org/projects/life-cycle-costing-tools?id=" + reports_load_path( I18n.locale, @report.id )
      / = link_to "#{request.protocol}#{request.host_with_port}" + reports_load_path( I18n.locale, @report.id ), reports_load_path( I18n.locale, @report.id ), { :class => 'share_report--link' }

    .standalone_form--footer
      .standalone_form--buttons.standalone_form--buttons-centred
        = link_to t( 'report.back' ), @back_path, :class => 'button'