config/routes.rb
require 'api_constraints'

WashCostApp::Application.routes.draw do
  use_doorkeeper do
    #controllers :applications => 'applications'
  end
  

  match '/infographic' => 'infographic#index'
  match '/infographic/mobile' => 'mobile#infographic'

  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      #devise_for :users

      get '/me' => 'users#me'
      get '/reports' => 'users#reports'
      get '/report/:id' => 'users#reports'

      scope '/water' do
        post '/create' => 'water#create'
        post '/update/:id' => 'water#update'
      end

      scope '/sanitation' do
        post '/create' => 'sanitation#create'
        post '/update/:id' => 'sanitation#update'
      end

      match '*not_found', to: 'base#api_not_found'
    end
  end

  scope "(:locale)", :locale => /en|fr|bn/ do

    devise_scope :user do
      get 'users' => 'authentication/registrations#new'
    end

    devise_scope :user do
      get 'users/password' => 'authentication/passwords#new'
    end

    devise_for :users, :controllers => { :sessions => 'authentication/sessions', :registrations => 'authentication/registrations', :passwords => 'authentication/passwords' }

    resources :dashboard

    scope '/calculators' do

      namespace :basic do

        scope '/water' do
          get '/begin' => 'water#begin', :as => 'water_begin'
          get '/report' => 'water#report', :as => 'water_report'
          get '/report/save' => 'water#save_report', :as => 'water_save_report'
          post '/report/save' => 'water#store_report', :as => 'water_store_report'
          get '/report/share' => 'water#share_report', :as => 'water_share_report'
          get '/:section' => 'water#questionnaire', :as => 'water_action'
          post '/update/:section' => 'water#update', :as => 'water_update'
          post '/dynamic_update' => 'water#dynamic_update', :as => 'water_dynamic_update'
          root :to => redirect( '/%{locale}/calculators/basic/water/country' ), :as => 'water'
        end

        scope '/sanitation' do
          get '/begin' => 'sanitation#begin', :as => 'sanitation_begin'
          get '/report' => 'sanitation#report', :as => 'sanitation_report'
          get '/report/save' => 'sanitation#save_report', :as => 'sanitation_save_report'
          post '/report/save' => 'sanitation#store_report', :as => 'sanitation_store_report'
          get '/report/share' => 'sanitation#share_report', :as => 'sanitation_share_report'
          get '/:section' => 'sanitation#questionnaire', :as => 'sanitation_action'
          post '/update/:section' => 'sanitation#update', :as => 'sanitation_update'
          post '/dynamic_update' => 'sanitation#dynamic_update', :as => 'sanitation_dynamic_update'
          root :to => redirect( '/%{locale}/calculators/basic/sanitation/country' ), :as => 'sanitation'
        end

      end

      namespace :advanced do

        scope '/water' do
          get '/begin' => 'water#begin', :as => 'water_begin'
          get '/report' => 'water#report', :as => 'water_report'
          get '/report/save' => 'water#save_report', :as => 'water_save_report'
          post '/report/save' => 'water#store_report', :as => 'water_store_report'
          get '/report/share' => 'water#share_report', :as => 'water_share_report'
          get '/:section' => 'water#questionnaire', :as => 'water_action'
          post '/update/:section' => 'water#update', :as => 'water_update'
          post '/dynamic_update' => 'water#dynamic_update', :as => 'water_dynamic_update'
          root :to => redirect( '/%{locale}/calculators/advanced/water/service_area' ), :as => 'water'
        end

        scope '/sanitation' do
          get '/begin' => 'sanitation#begin', :as => 'sanitation_begin'
          get '/report' => 'sanitation#report', :as => 'sanitation_report'
          get '/report/save' => 'sanitation#save_report', :as => 'sanitation_save_report'
          post '/report/save' => 'sanitation#store_report', :as => 'sanitation_store_report'
          get '/report/share' => 'sanitation#share_report', :as => 'sanitation_share_report'
          get '/:section' => 'sanitation#questionnaire', :as => 'sanitation_action'
          post '/update/:section' => 'sanitation#update', :as => 'sanitation_update'
          post '/dynamic_update' => 'sanitation#dynamic_update', :as => 'sanitation_dynamic_update'
          root :to => redirect( '/%{locale}/calculators/advanced/sanitation/service_area' ), :as => 'sanitation'
        end

      end

      post '/selection' => 'calculators#selection'

      root :to => 'calculators#index', :as => 'calculators'

    end

    get '/dashboard' => 'dashboard#index', :as => 'dashboard'
    get '/report/destroy/:id' => 'reports#destroy', :as => 'reports_destroy'
    get '/report/:id' => 'reports#load', :as => 'reports_load'
    put '/report' => 'reports#update', :as => 'report'

    root :to => 'landing#index', :as => 'localised_root'

  end

  root :to => redirect( "/#{I18n.default_locale}/" )

end

app/controllers/advanced/water_controller.rb
class Advanced::WaterController < CalculatorController

  include ApplicationHelper

  layout 'tool_advanced'

  authorize_resource :class => Advanced::WaterController
  load_and_authorize_resource UserReport, :only => [ :save_report, :store_report ]


  def begin
    @questionnaire = AdvancedWaterQuestionnaire.new( session )
    @questionnaire.reset

    redirect_to advanced_water_action_path( I18n.locale, :service_area, :start => true )
  end

  def questionnaire
    if params[ :start ] != nil
      session[:advanced_water][:currency] = nil
      session[:advanced_water][:country] = nil
      session[:advanced_water][:status] = nil
      session[:advanced_water][:year_of_expenditure] = nil
    end
    @questionnaire = AdvancedWaterQuestionnaire.new( session )

    render params[ :section ]
  end

  def update
    @questionnaire = AdvancedWaterQuestionnaire.new( session )
    
    # save updated questionnaire
    @questionnaire.update_attributes( params[ :advanced_water_questionnaire ] )

    redirect_to advanced_water_action_path( I18n.locale, params[ :section ] )
  end

  def dynamic_update
    @questionnaire = AdvancedWaterQuestionnaire.new( session )

    # save updated questionnaire
    @questionnaire.update_attributes( params[ :advanced_water_questionnaire ] )

    render json: { :progress => @questionnaire.complete }
  end

  def report
    @questionnaire = AdvancedWaterQuestionnaire.new( session )

    # No choice but to do the following

    benchmark = Hash.new()
    benchmark_moe_new = []
    benchmark_dsc_new = []    
    out = final_usd_2011_number(@questionnaire.attributes, 1)

    if out != nil

      @questionnaire.benchmark_minor_operation_expenditure.each do |val|
        if benchmark.has_key?(val.to_s) == false
          newvalue = "#{number_with_precision( val.to_f / out.to_f, :precision => 5 )}"
          benchmark[val] = newvalue.to_s
          benchmark_moe_new.push(newvalue.to_s)
        else
          benchmark_moe_new.push(benchmark[val])
        end
      end

      @questionnaire.benchmark_direct_support_cost.each do |val|
        if benchmark.has_key?(val) == false
          newvalue = "#{number_with_precision( val.to_f / out.to_f, :precision => 5 )}"
          benchmark[val] = newvalue.to_s
          benchmark_dsc_new.push(newvalue.to_s)
        else
          benchmark_dsc_new.push(benchmark[val])
        end
      end

    end

    @questionnaire.benchmark_moe = benchmark_moe_new
    @questionnaire.benchmark_dsc = benchmark_dsc_new

    render layout: 'report'
  end

  def save_report
    @report = UserReport.new

    render layout: 'general', template: 'shared/save_report'
  end

  def share_report

    @report = Report.create( :level => 'advanced', :type => 'water', :questionnaire => AdvancedWaterQuestionnaire.new( session ).attributes )
    @back_path = advanced_water_report_path( I18n.locale )

    render layout: 'general', template: 'shared/share_report'
  end

  def store_report

    # Added logic here, to remove on the fly database rendering and calculations from views
    # calculations and logic called here and saved to the database
    # couldn't go to deep without re-writing all logic and models

    avq = AdvancedWaterQuestionnaire.new( session )
    questionnaire = avq.attributes

    cepp = final_usd_2011(questionnaire, capital_expenditure_per_person(questionnaire)).to_s
    repppy = final_usd_2011(questionnaire, recurrent_expenditure_per_person_per_year(questionnaire, 30)).to_s
    poptman = percentage_of_population_that_meets_all_norms(questionnaire).to_s

    # benchmark_moe = Hash.new()
    # benchmark_moe_new = []
    # benchmark_dsc_new = []
    # out = final_usd_2011_number(questionnaire, 1)

    # if out != nil

    #   for i in avq.benchmark_minor_operation_expenditure
    #     val = avq.benchmark_minor_operation_expenditure[i]
    #     if benchmark_moe.has_key?(val) == false
    #       newvalue = "#{number_with_precision( val.to_f / out.to_f, :precision => 5 )}"
    #       benchmark_moe[val] = newvalue.to_s
    #       benchmark_dsc_new.push(newvalue.to_s)
    #     else
    #       benchmark_moe_new.push(benchmark_moe[val])
    #     end
    #   end

    #   for i in avq.benchmark_direct_support_cost
    #     val = avq.benchmark_direct_support_cost[i]
    #     if benchmark_moe.has_key?(val) == false
    #       newvalue = "#{number_with_precision( val.to_f / out.to_f, :precision => 5 )}"
    #       benchmark_moe[val] = newvalue.to_s
    #       benchmark_dsc_new.push(newvalue.to_s)
    #     else
    #       benchmark_dsc_new.push(benchmark_moe[val])
    #     end
    #   end

    # end

    # questionnaire[:benchmark_moe] = benchmark_moe_new
    # questionnaire[:benchmark_dsc] = benchmark_dsc_new

    super( params[ :user_report ][ :title ], 'advanced', session[:advanced_water][:status], 'water', questionnaire, cepp, repppy, poptman)
  end

end

app/controllers/basic/sanitation_controller.rb
class Basic::SanitationController < CalculatorController

  layout 'tool_basic'

  load_and_authorize_resource UserReport, :only => [ :save_report, :store_report ]


  def begin
    @questionnaire = BasicSanitationQuestionnaire.new( session )
    @questionnaire.reset

    redirect_to basic_sanitation_action_path( I18n.locale, :country )
  end

  def questionnaire
    @questionnaire = BasicSanitationQuestionnaire.new( session )

    render params[ :section ]
  end

  def update
    @questionnaire = BasicSanitationQuestionnaire.new( session )

    # save updated questionnaire
    @questionnaire.update_attributes( params[ :basic_sanitation_questionnaire ] )

    redirect_to basic_sanitation_action_path( I18n.locale, params[ :section ] )
  end

  def dynamic_update
    @questionnaire = BasicSanitationQuestionnaire.new( session )

    # save updated questionnaire
    @questionnaire.update_attributes( params[ :basic_sanitation_questionnaire ] )

    render json: { :progress => @questionnaire.complete }
  end

  def report
    @questionnaire = BasicSanitationQuestionnaire.new( session )

    render layout: 'report'
  end

  def save_report
    @report = UserReport.new

    render layout: 'general', template: 'shared/save_report'
  end

  def share_report
    @report = Report.create( :level => 'basic', :type => 'sanitation', :questionnaire => BasicSanitationQuestionnaire.new( session ).attributes )
    @report.save
    @back_path = basic_sanitation_report_path( I18n.locale )

    render layout: 'general', template: 'shared/share_report'
  end

  def store_report
    super( params[ :user_report ][ :title ], 'basic', session[:basic_sanitation][:status], 'sanitation', BasicSanitationQuestionnaire.new( session ).attributes, "NA", "N/A", "0%" )
  end

end

app/helpers/basic/navigation_helper.rb
module Basic::NavigationHelper
  # return just the items of each section in an specific questionnaire
  # @return [Array], each element contains Hash with attr used in the navigation (name, link and css class)
  def questionnaire_items_list
    current_path = navigation_context[:path]
    items = questionnaire_items
    items.map do |k,v|
      {
          name: v,
          link: k.to_s,
          class: item_class_by_action(k),
      }
    end
  end

  # return a Hash Set with the attributtes of each nav section (name, link and css class)
  # @return [Array]
  def questionnaire_sections
    current_path = navigation_context[:path]
    sections = navigation_context.select{|k,v| v.is_a?(Hash)}.keys
    sections.map do |section|
      {
          name: navigation_context[section][:name],
          redirect_to: navigation_context[section][:first_action],
          number_of_items: navigation_context[section][:items].length,
          class: navigation_context[section.to_sym][:items].has_key?(controller.action_name.to_sym) ? "active" : "",
      }
    end
  end

  # return an array with the items associated to each section
  # @return [Array]
  def index_questionnaire_item_active
    items = questionnaire_items
    items.each_with_index do |item|
    end
  end

  private

  # return just the items of each section in an specific questionnaire
  # @return [Hash Set], each element contains Hash with attr used in the navigation (name, link and css class)
  def questionnaire_items
    navigation_context.map{|k,v| v.is_a?(Hash) ? v[:items] : nil}.compact.reduce do |a, b|
      a.merge(b) { |k, v1, v2| v1 == v2 ? v1 : [v1, v2].flatten }
    end
  end

  # return the css class associated with specific state of item (.active, .resolved or nothing)
  # @return [String]
  def item_class_by_action(action)
    form = "#{controller.controller_name}_form".to_sym
    if action.to_s == controller.action_name
      "active"
    elsif session[form].present? && session[form].has_key?(action.to_s)
      "resolved"
    end
  end

  # return the data associated with all navigation about the basic tool specified
  # @return [Hash]
  def navigation_context
    if controller.controller_name == "sanitation_basic"
      {
          path: cal_sanitation_basic_path,
          context: {
              offset: '0',
              name: I18n.t('nav.main.context.title'),
              first_action: :country,
              items: {
                  country: I18n.t('nav.main.context.items.country'),
                  population: I18n.t('nav.main.context.items.population'),
                  latrine: I18n.t('nav.main.context.items.latrine'),
              }
          },
          cost: {
              offset: '-280',
              first_action: :capital,
              name: I18n.t('nav.main.cost.title'),
              items: {
                  capital: I18n.t('nav.main.cost.items.capital'),
                  recurrent: I18n.t('nav.main.cost.items.recurrent')
              }
          },
          service: {
              offset:'-430',
              first_action: :providing,
              name: I18n.t('nav.main.service.title'),
              items: {
                  providing: I18n.t('nav.main.service.items.providing'),
                  impermeability: I18n.t('nav.main.service.items.impermeability'),
                  environment: I18n.t('nav.main.service.items.environment'),
                  usage: I18n.t('nav.main.service.items.usage')      ,
                  reliability: I18n.t('nav.main.service.items.reliability')
              }
          }
      }
    elsif controller.controller_name == "water_basic"
      {
          path: cal_water_basic_path,
          context: {
              offset: '0',
              name: I18n.t('nav.main.context.title'),
              first_action: :country,
              items: {
                  country: I18n.t('nav.main.context.items.country'),
                  water: I18n.t('nav.main.context.items.water'),
                  population: I18n.t('nav.main.context.items.population')
              }
          },
          cost: {
              offset: '-210',
              first_action: :capital,
              name: I18n.t('nav.main.cost.title'),
              items: {
                  capital: I18n.t('nav.main.cost.items.capital'),
                  recurrent: I18n.t('nav.main.cost.items.recurrent')
              }
          },
          service: {
              offset: '-210',
              first_action: :time,
              name: I18n.t('nav.main.service.title'),
              items: {
                  time: I18n.t('nav.main.service.items.time'),
                  quantity: I18n.t('nav.main.service.items.quantity'),
                  quality: I18n.t('nav.main.service.items.quality'),
                  reliability: I18n.t('nav.main.service.items.reliability')
              }
          }
      }
    else
      {
          path: cal_water_advanced_path,
          advanced: {
              offset: '0',
              name: I18n.t('nav.main.advanced.title'),
              first_action: :advanced,
              items: {
                  context: I18n.t('nav.main.advanced.items.context'),
                  system_management: I18n.t('nav.main.advanced.items.system_management'),
                  system_characteristics: I18n.t('nav.main.advanced.items.system_characteristics'),
                  cost: I18n.t('nav.main.advanced.items.cost'),
                  services: I18n.t('nav.main.advanced.items.service')
              }
          }
      }
    end
  end
end

app/views/basic/water/access.html.haml
= content_for :title do
  6 of 9 (Access) - Basic Water Calculator

.question
  %h1.question--title= t 'basic.water.questionnaire.access.question'

  .question--answer

    .question--answer--title= t 'basic.shared.questionnaire.minutes_per_day'

    = form_for @questionnaire, :url => basic_water_update_url( I18n.locale, 'quantity' ), :html => { 'data-dynamic_form' => basic_water_dynamic_update_url( I18n.locale ) } do |f|

      .question--radios
        - options_for_water_access.each do |option|
          = f.label( "access_#{option[1]}", class: "question--radios--label" ) do
            = f.radio_button :access, option[1], :class => 'question--radios--radio'
            %span.question--checked_icon
            %span{ :class => "question--radios--icon icon--tool-#{option[0]}" }
            %span.question--radios--text= t "basic.water.questionnaire.access.options.#{option[0]}"

      -#.slider.slider-time
        -#%input.slider--value.slider--value-wide{ :type => 'text', :value => @questionnaire.access != nil ? @questionnaire.access : 0, :readonly => 'true' }
        -#.slider--widget
        -#= f.hidden_field :access, { :value => @questionnaire.access != nil ? @questionnaire.access : 0, 'data-slider-input' => 'true', 'data-slider-min' => @questionnaire.minimum_access, 'data-slider-max' => @questionnaire.maximum_access, 'data-slider-values' => options_for_water_access.to_s }

      .question--buttons
        = submit_tag t( 'buttons.next' ), :class => 'button'

.info_tab
  .info_tab--icon
  .info_tab--container
    .info_tab--content
      %p.info_tab--content--text= raw format_info_text 'basic.water.questionnaire.access.info'

app/views/basic/water/capital_expenditure.html.haml
= content_for :title do
  4 of 9 (Capital Expenditure) - Basic Water Calculator

.question
  %h1.question--title= t('basic.water.questionnaire.capital_expenditure.question')

  .question--answer

    .question--answer--title= t 'basic.shared.questionnaire.per_person_usd'

    = form_for @questionnaire, :url => basic_water_update_url( I18n.locale, 'recurrent_expenditure' ), :html => { 'data-dynamic_form' => basic_water_dynamic_update_url( I18n.locale ) } do |f|

      .slider
        %input.slider--value{ 'data-target' => 'capitalSlider', :value => @questionnaire.capital_expenditure != nil ? @questionnaire.capital_expenditure : @questionnaire.minimum_capital_expenditure }
        .slider--widget.threshold-marks
        = f.hidden_field :capital_expenditure, { :value => @questionnaire.capital_expenditure != nil ? @questionnaire.capital_expenditure : @questionnaire.minimum_capital_expenditure, 'data-slider-input' => 'true', 'data-slider-min' => @questionnaire.minimum_capital_expenditure, 'data-slider-max' => @questionnaire.maximum_capital_expenditure, 'data-slider-below' => @questionnaire.minimum_guidance_capital_expenditure, 'data-slider-above' => @questionnaire.maximum_guidance_capital_expenditure }

        .slider--scale
          .slider--scale--point.slider--scale--point-min= "US$ #{@questionnaire.minimum_guidance_capital_expenditure}"
          .slider--scale--point.slider--scale--point-max= "US$ #{@questionnaire.maximum_guidance_capital_expenditure}"

      .question--buttons
        = submit_tag t( 'buttons.next' ), :class => 'button'

.info_tab
  .info_tab--icon
  .info_tab--container
    .info_tab--content
      %p.info_tab--content--text= raw format_info_text 'basic.water.questionnaire.capital_expenditure.info'

app/views/basic/water/country.html.haml
= content_for :title do
  Start - Basic Water Calculator

.question
  %h1.question--title= t('basic.shared.questionnaire.country.question')

  .question--answer

    .question--image.icon--tool-globe

    = form_for @questionnaire, :url => basic_water_update_url( I18n.locale, 'technology' ), :html => { 'data-dynamic_form' => basic_water_dynamic_update_url( I18n.locale ) } do |f|

      .choices-select
        = f.select :country, options_for_select( options_for_countries, @questionnaire.country ), { :include_blank => t( 'basic.shared.questionnaire.country.placeholder' ) }, { :tabindex => '1', :class=>"chzn-select" }

      .question--buttons
        = submit_tag t( 'buttons.next' ), :class => 'button', :tabindex => '2'

.info_tab
  .info_tab--icon
  .info_tab--container
    .info_tab--content
      %p.info_tab--content--text= raw format_info_text 'basic.shared.questionnaire.country.info'

app/views/basic/water/population.html.haml
= content_for :title do
  3 of 9 (Population) - Basic Water Calculator

.question
  %h1.question--title= @questionnaire.technology != nil ? t( 'basic.water.questionnaire.population.question', :technology => t( "basic.water.questionnaire.technology.options.#{options_for_water_supply_technologies[@questionnaire.technology.to_i][0]}" ) ) : t( 'basic.water.questionnaire.population.default_question' )

  .question--answer

    .question--answer--title= t 'basic.shared.questionnaire.people'

    = form_for @questionnaire, :url => basic_water_update_url( I18n.locale, 'capital_expenditure' ), :html => { 'data-dynamic_form' => basic_water_dynamic_update_url( I18n.locale ) } do |f|

      .slider
        %input.slider--value{ :type => 'text', :value => @questionnaire.population != nil ? number_with_precision( @questionnaire.population, :precision => 1, :locale => I18n.locale ) : @questionnaire.minimum_population }
        .slider--widget
        = f.hidden_field :population, { :value => @questionnaire.population ? @questionnaire.population : @questionnaire.minimum_population, 'data-slider-input' => 'true', 'data-logarithmic' => 'true', 'data-slider-min' => @questionnaire.minimum_population, 'data-slider-max' => @questionnaire.maximum_population }

      .question--buttons
        = submit_tag t( 'buttons.next' ), :class => 'button'

.info_tab
  .info_tab--icon
  .info_tab--container
    .info_tab--content
      %p.info_tab--content--text= raw format_info_text 'basic.water.questionnaire.population.info'

app/views/basic/water/quality.html.haml
= content_for :title do
  8 of 9 (Quality) - Basic Water Calculator

.question
  %h1.question--title= t 'basic.water.questionnaire.quality.question'

  .question--answer

    = form_for @questionnaire, :url => basic_water_update_url( I18n.locale, 'reliability' ), :html => { 'data-dynamic_form' => basic_water_dynamic_update_url( I18n.locale ) } do |f|

      .question--radios
        - options_for_water_qualities.each do |option|
          = f.label( "quality_#{option[1]}", class: "question--radios--label" ) do
            = f.radio_button :quality, option[1], :class => 'question--radios--radio'
            %span.question--checked_icon
            %span{ :class => "question--radios--icon icon--tool-#{option[0]}" }
            %span.question--radios--text= t "basic.water.questionnaire.quality.options.#{option[0]}"

      .question--buttons
        = submit_tag t( 'buttons.next' ), :class => 'button'

.info_tab
  .info_tab--icon
  .info_tab--container
    .info_tab--content
      %p.info_tab--content--text= raw format_info_text 'basic.water.questionnaire.quality.info'

app/views/basic/water/quantity.html.haml
= content_for :title do
  7 of 9 (Water Source) - Basic Water Calculator

.question
  %h1.question--title= t 'basic.water.questionnaire.quantity.question'

  .question--answer

    .question--answer--title= t 'basic.water.questionnaire.quantity.label'

    = form_for @questionnaire, :url => basic_water_update_url( I18n.locale, 'quality' ), :html => { 'data-dynamic_form' => basic_water_dynamic_update_url( I18n.locale ) } do |f|

      .question--radios
        - options_for_water_quantities.each do |option|
          = f.label( "quantity_#{option[1]}", class: "question--radios--label" ) do
            = f.radio_button :quantity, option[1], :class => 'question--radios--radio'
            %span.question--checked_icon
            %span{ :class => "question--radios--icon icon--tool-#{option[0]}" }
            %span.question--radios--text= t "basic.water.questionnaire.quantity.options.#{option[0]}"

      .question--buttons
        = submit_tag t( 'buttons.next' ), :class => 'button'

.info_tab
  .info_tab--icon
  .info_tab--container
    .info_tab--content
      %p.info_tab--content--text= raw format_info_text 'basic.water.questionnaire.quantity.info'

app/views/basic/water/recurrent_expenditure.html.haml
= content_for :title do
  5 of 9 (Recurrent Expenditure) - Basic Water Calculator

.question
  %h1.question--title= t('basic.water.questionnaire.recurrent_expenditure.question')

  .question--answer

    .question--answer--title= t 'basic.share.usd_per_person_per_year'

    = form_for @questionnaire, :url => basic_water_update_url( I18n.locale, 'access' ), :html => { 'data-dynamic_form' => basic_water_dynamic_update_url( I18n.locale ) } do |f|

      .slider
        %input.slider--value{ 'data-target' => 'recurrentSlider', :value => @questionnaire.recurrent_expenditure != nil ? @questionnaire.recurrent_expenditure : @questionnaire.minimum_recurrent_expenditure }
        .slider--widget.threshold-marks
        = f.hidden_field :recurrent_expenditure, { :value => @questionnaire.recurrent_expenditure != nil ? @questionnaire.recurrent_expenditure : @questionnaire.minimum_recurrent_expenditure, 'data-slider-input' => 'true', 'data-slider-min' => @questionnaire.minimum_recurrent_expenditure, 'data-slider-max' => @questionnaire.maximum_recurrent_expenditure, 'data-slider-below' => @questionnaire.minimum_guidance_recurrent_expenditure, 'data-slider-above' => @questionnaire.maximum_guidance_recurrent_expenditure }

        .slider--scale
          .slider--scale--point.slider--scale--point-min= "US$ #{@questionnaire.minimum_guidance_recurrent_expenditure}"
          .slider--scale--point.slider--scale--point-max= "US$ #{@questionnaire.maximum_guidance_recurrent_expenditure}"

      .question--buttons
        = submit_tag t( 'buttons.next' ), :class => 'button'

.info_tab
  .info_tab--icon
  .info_tab--container
    .info_tab--content
      %p.info_tab--content--text= raw format_info_text 'basic.water.questionnaire.recurrent_expenditure.info'

app/views/basic/water/reliability.html.haml
= content_for :title do
  9 of 9 (Reliability) - Basic Water Calculator

.question
  %h1.question--title= t 'basic.water.questionnaire.reliability.question'

  .question--answer

    = form_for @questionnaire, :url => basic_water_update_url( I18n.locale, 'report' ), :html => { 'data-dynamic_form' => basic_water_dynamic_update_url( I18n.locale ) } do |f|

      .question--radios
        - options_for_water_reliability.each do |option|
          = f.label( "reliability_#{option[1]}", :class => "question--radios--label" ) do
            = f.radio_button :reliability, option[1], :class => 'question--radios--radio'
            %span.question--checked_icon
            %span{ :class => "question--radios--icon icon--tool-#{option[0]}" }
            %span.question--radios--text= t "basic.water.questionnaire.reliability.options.#{option[0]}"

      .question--buttons
        = submit_tag t( 'buttons.view_report' ), :class => 'button'

.info_tab
  .info_tab--icon
  .info_tab--container
    .info_tab--content
      %p.info_tab--content--text= raw format_info_text 'basic.water.questionnaire.reliability.info'

app/views/basic/water/technology.html.haml
= content_for :title do
  2 of 9 (Technology) - Basic Water Calculator

.question
  %h1.question--title= t 'basic.water.questionnaire.technology.question'

  .question--answer

    = form_for @questionnaire, :url => basic_water_update_url( I18n.locale, 'population' ), :html => { 'data-dynamic_form' => basic_water_dynamic_update_url( I18n.locale ) } do |f|

      .question--radios
        - options_for_water_supply_technologies.each do |option|
          = f.label( "technology_#{option[1]}", class: "question--radios--label" ) do
            = f.radio_button( :technology, option[1], :class => 'question--radios--radio' )
            %span.question--checked_icon
            %span{ :class => "question--radios--icon icon--tool-#{option[0]}" }
            %span.question--radios--text= t( "basic.water.questionnaire.technology.options.#{option[0]}" )

      .question--buttons
        = submit_tag t( 'buttons.next' ), :class => 'button', :tabindex => '6'

.info_tab
  .info_tab--icon
  .info_tab--container
    .info_tab--content
      %p.info_tab--content--text= raw format_info_text 'basic.water.questionnaire.technology.info'